name: CI

on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: "3.12"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
